---
title: "Four Factorsで勝敗を予測する――2020-21シーズンの千葉・宇都宮・川崎・琉球のデータを使って"
author: "rnsr0371"
date: "8/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
こんにちは、らんそうるい（[rnsr0371](https://twitter.com/rnsr0371)）です。ロジスティック回帰分析の練習として、Four Factors（eFG、ターンオーバー率、フリースロー率、オフェンシブリバウンド率）で試合の勝敗を分析してみました。分析のアイディアは[Kazuki KIMURA](https://twitter.com/xka_zux13)様からいただきました。ありがとうございました。

## 問題
ロジスティック回帰分析を使うと、勝敗のような二値変数を従属変数に置いて、独立変数、ここではFour Factorsとの関係を調べることができます。調べることができるのは、たとえば、攻撃のeFGが高いほど試合に勝ちやすいか、といった関係です。  
ここで問題にしたいのは、チームごとにFour Factorsと試合の勝敗の関係は変わるのか？　ということです。つまり、たとえば、あるチームでは自チームのオフェンシブリバウンド率と勝敗に関係は見られないけれど、別のチームでは勝敗に関係が見られるか？　という問題です。この問題を調べるために、千葉・宇都宮・川崎・琉球の2020-21シーズンのベスト4チームのデータを使って、Four Factorsで勝敗をロジスティック回帰分析してみました。今回は攻撃側のFour Factorsのみを使った分析を紹介いたします。


## 分析
### データの準備
[rintaromasuda様のGitHub](https://github.com/rintaromasuda/bleaguer/tree/master/inst/extdata)からteams.csvとgames_summary_202021.csvをダウンロードし、これらを生データとしました。さらに、games_summary_202021.csvから千葉・宇都宮・川崎・琉球のデータを抽出しました。抽出したデータに勝敗（勝ち=1、負け=０）、標準化したFour Factors、宇都宮を表すダミー変数(宇都宮=1、それ以外=0)、川崎を表すダミー変数(川崎=1、それ以外=0)、琉球を表すダミー変数(琉球=1、それ以外=0)を追加してデータセットとしました。

### 分析
```{R echo=F,include=FALSE}
#必要なライブラリのインポート
library(tidyverse)

#データのインポート
teams=read_csv("../data/teams.csv")
score=read_csv("../data/games_summary_202021.csv")

#teamsから2020-21シーズンのB1のデータだけ抽出
teams=teams %>% filter(Season=="2020-21") %>% filter(League=="B1")

#scoreからB1のデータだけ抽出
score=teams %>% left_join(score,by="TeamId")

#scoreに勝敗を追加する
score=score %>% arrange(ScheduleKey)
k=seq(1,1147,2)
g=seq(2,1148,2)

diff_score_k=score$PTS[k]-score$PTS[g]
diff_score_g=score$PTS[g]-score$PTS[k]

score=rbind(score[k,],score[g,])
score=score %>% mutate(diff=c(diff_score_k,diff_score_g))

score=score %>% mutate(win=ifelse(diff>0,1,0))#勝った場合は1

score=score %>% arrange(ScheduleKey)

#FourFactorsを計算する
#eFG
eFG_k=(score$F2GM[g]+1.5*score$F3GM[g])/(score$F2GA[g]+score$F3GA[g])
eFG_g=(score$F2GM[k]+1.5*score$F3GM[k])/(score$F2GA[k]+score$F3GA[k])
score=rbind(score[k,],score[g,])
score=score %>% mutate(D_eFG=c(eFG_k,eFG_g))
score=score %>% mutate(eFG=(F2GM+1.5*F3GM)/(F2GA+F3GA))
score=score %>% arrange(ScheduleKey)

#TO%
TOP_k=(score$TO[g]/(score$F2GA[g]+score$F3GA[g]+0.44*score$FTA[g]+score$TO[g]))
TOP_g=(score$TO[k]/(score$F2GA[k]+score$F3GA[k]+0.44*score$FTA[k]+score$TO[k]))
score=rbind(score[k,],score[g,])
score=score %>% mutate(D_TOP=c(TOP_k,TOP_g))
score=score %>% mutate(TOP=TO/(F2GA+F3GA+0.44*FTA+TO))
score=score %>% arrange(ScheduleKey)

#FT%
FTP_k=(score$FTA[g]/(score$F2GA[g]+score$F3GA[g]))
FTP_g=(score$FTA[k]/(score$F2GA[k]+score$F3GA[k]))
score=rbind(score[k,],score[g,])
score=score %>% mutate(D_FTP=c(FTP_k,FTP_g))
score=score %>% mutate(FTR=FTA/(F2GA+F3GA))
score=score %>% arrange(ScheduleKey)

#ORBP
ORBP_g=score$OR[k]/(score$OR[k]+score$DR[g])
ORBP_k=score$OR[g]/(score$OR[g]+score$DR[k])
score=rbind(score[k,],score[g,])
score=score %>% mutate(D_ORBP=c(ORBP_k,ORBP_g))
score=score %>% arrange(ScheduleKey)
ORBP_g=score$OR[g]/(score$OR[g]+score$DR[k])
ORBP_k=score$OR[k]/(score$OR[k]+score$DR[g])
score=rbind(score[k,],score[g,])
score=score %>% mutate(ORBP=c(ORBP_k,ORBP_g))
score=score %>% arrange(ScheduleKey)
library(corrplot)
```
まずFour Factors同士の相関係数を示します。TOPはターンオーバー率、FTRはフリースロー率、ORBPはオフェンシブリバウンド率です。
```{R}
#FourFatorsの相関係数を確認
score %>% select(eFG,TOP,FTR,ORBP) %>% cor(.) %>% corrplot.mixed(.)
```
  
この相関行列から、Four Factors同士の相関はほとんどなく、多重共線性の心配はしなくて良いと考えられました。  
Four Factorsと、Four Factorsとダミー変数の交互作用項(全部で12個の交互作用項があります)を独立変数、勝敗を従属変数にロジスティック回帰分析を行いました。
```{R echo=F,include=F}
#FourFatorsを標準化する
score=score %>% mutate(eFG_z=scale(eFG),TOP_z=scale(TOP),FTR_z=scale(FTR),ORBP_z=scale(ORBP))
score=score %>% mutate(D_eFG_z=scale(D_eFG),D_TOP_z=scale(D_TOP),D_FTP_z=scale(D_FTP),D_ORBP_z=scale(D_ORBP))

#千葉、宇都宮、川崎、琉球のデータを抽出
chiba=score %>% filter(NameShort=="千葉")
utsunomiya=score %>% filter(NameShort=="宇都宮")
kawasaki=score %>% filter(NameShort=="川崎")
ryukyu=score %>% filter(NameShort=="琉球")

#ダミー変数を使ってデータをまとめて分析する（記事で使った分析。攻撃側のFour Factorsのみ使用）
best4=rbind(chiba,utsunomiya,kawasaki,ryukyu)
best4$utsunomiya=ifelse(best4$NameShort=="宇都宮",1,0)
best4$kawasaki=ifelse(best4$NameShort=="川崎",1,0)
best4$ryukyu=ifelse(best4$NameShort=="琉球",1,0)
```
```{R}
#ダミー変数を使ったロジスティック回帰
model=best4 %>% select(win,eFG_z,TOP_z,FTR_z,ORBP_z,utsunomiya,kawasaki,ryukyu) %>% 
  glm(win~eFG_z+TOP_z+FTR_z+ORBP_z+
        eFG_z:utsunomiya+TOP_z:utsunomiya+FTR_z:utsunomiya+ORBP_z:utsunomiya+
        eFG_z:kawasaki+TOP_z:kawasaki+FTR_z:kawasaki+ORBP_z:kawasaki+
        eFG_z:ryukyu+TOP_z:ryukyu+FTR_z:ryukyu+ORBP_z:ryukyu,
      data=.,family = binomial)

summary(model)
```
その結果、5%水準で有意だったのはeFGの主効果、琉球xフリースロー率の交互作用、琉球xオフェンシブリバウンド率の交互作用でした。偏回帰係数を確認すると、eFGは全チームに共通して高ければ高いほど試合に勝ちやすいことが分かりました。また、琉球に限っては、オフェンシブリバウンド率とフリースロー率が高ければ高いほど試合に勝ちやすいことが分かりました。琉球にはリバウンドに強いジャック・クーリー選手がいるので、彼がオフェンスリバウンドを取れるか？　フリースローを獲得できるか？　が勝敗に関係していることが、交互作用が有意になった理由なのではないかと思います。

## 終わりに
この記事ではFour Factorsと勝敗について分析を行いました。また、千葉・宇都宮・川崎・琉球の4チームでFour Factorsと勝敗の関係が異なるかを調べました。その結果、4チームともeFGが高いほど試合に勝ちやすいことが分かりました。また、琉球に限っては、フリースロー率とオフェンシブリバウンド率が高いほど試合に勝ちやすいことが分かりました。  
ロジスティック回帰や交互作用の使用は不慣れなので、分析に間違いが含まれているかもしれません。もし不備にお気づきになったら、Twitterで教えていただけると嬉しいです。
